name: Deploy React App on Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # Runs on your self-hosted runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: 'yarn'  # Use 'npm' if using npm

      - name: Install Dependencies
        run: yarn install  # Use `npm install` if using npm

      - name: Build React App
        run: yarn build  # Use `npm run build` if using npm

      - name: Deploy to Server
        run: |
          rm -rf /var/www/reactapp/*
          cp -r build/* /var/www/reactapp/
          sudo systemctl restart nginx  # Restart Nginx if needed

